modLoader = "lowcodefml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/JEIModelBridge/issues"

[[mods]]
	modId = "jeimodelbridge"
	version = "0@VERSION@"
	displayName = "JEIModelBridge"
	description = "Patches JEI's item model wrapper to also implement Fabric model extensions."
	logoFile = "jeimodelbridge.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/jeimodelbridge"

[[mixins]]
	config = "jeimodelbridge.mixins.json"

[[dependencies.jeimodelbridge]]
	modId = "minecraft"
	versionRange = "[1.21,1.21.2)"
	type = "required"

[[dependencies.jeimodelbridge]]
	modId = "jei"
	versionRange = "[19.21.1.304,)"
	type = "required"

[[dependencies.jeimodelbridge]]
	modId = "fabric_renderer_api_v1"
	versionRange = "[3,)"
	type = "required"
